name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to Server
        env:
          SSH_HOST: ubuntu@18.206.25.249
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no "$SSH_HOST" <<EOF
            set -euo pipefail
          
            PROJECT_DIR=/home/ubuntu/mevzuat
            VENV_DIR="$PROJECT_DIR/venv"

            # code update
            cd "$PROJECT_DIR"
            git fetch origin
            git reset --hard origin/main
            
            # python deps
            source "$VENV_DIR/bin/activate"
            pip install -r requirements.txt
            
            # Django mgmt
            python manage.py migrate --noinput || { echo "Migrations failed"; exit 1; }
            # python manage.py loaddata fixtures/* || { echo "Fixture load failed"; exit 1; }
            python manage.py createsuperuser --noinput || true
            python manage.py collectstatic --noinput || { echo "Collectstatic failed"; exit 1; }
          
            # Restart the server
            sudo systemctl restart mevzuat

            # Obtain/renew SSL certificate via certbot
            sudo certbot --nginx --non-interactive --agree-tos -m onurmatik@gmail.com -d mevzuat.info --redirect
          EOF
